

INSERT INTO Allergy(Name) VALUES
('Medicamentos'),
('Polietilenglicol'),
('Alimentos'),
('Medio ambiente'),
('Otros')

INSERT INTO Disease(Name) VALUES
('EnfermedadAddison'),
('Alergias'),
('Arritmias'),
('Fibrilacióauricular'),
('Vasculitiautoinmune'),
('ParálisidBel(parálisifacial)'),
('Bronquitis'),
('Cáncer'),
('Enfermedacelíac(intoleranciagluten)'),
('Enfermedarenacrónica'),
('Insuficiencicardíaccongestiva'),
('EnfermedadCrohn'),
('TV(coágulodsangre)'),
('Diabetes'),
('Encefaliti(inflamaciócerebral/doloredcabeza)'),
('Epilepsi(convulsiones)'),
('Enfermedadedecorazón'),
('Herpetip1'),
('Herpetip2'),
('VIH'),
('Hipertensió(presióarteriaalta)'),
('Enfermedainflamatoriintestinal'),
('Enfermedarenaaguda'),
('Enfermedahepática'),
('Lupus'),
('Abortespontáneo'),
('Esclerosimúltiple'),
('Miastenigravis'),
('Infartdmiocardi(ataquacorazón)'),
('Miocarditis'),
('Osteoartritis'),
('Pericarditis'),
('Anemiperniciosa'),
('Neumonía'),
('Partprematuro'),
('Psoriasis'),
('Artritipsoriásica'),
('Embolipulmonar'),
('Artritireumatoide'),
('Herpezóster'),
('SíndromdSjogren'),
('Nacimientsivida'),
('Accidentcerebrovascular'),
('Ataqueisquémicotransitorio(AIT)'),
('Trastorndltiroides'),
('Colitiulcerosa')

INSERT INTO Symptom(Name) VALUES
('SíntomadCOVIEnfermedadCOVID'),
('Disminuciódebienestar'),
('Disminuciódeestaddsalud'),
('Fatigextrema'),
('Incapacidaparparticipaeactividaderutinarias'),
('Pérdiddenergía'),
('Doloinexplicable'),
('Debilidad'),
('Fiebrinexplicable'),
('Sensacionecorporaleinexplicables'),
('Sudorenocturnos'),
('Sofocos'),
('Intoleranciafrío'),
('Intoleranciacalor'),
('Sensibilidalocambiodtemperatura'),
('Cambielcapacidadcaminar'),
('Cambieepensamiento'),
('Ynmsientcomantes'),
('Aumentdpesinexplicable'),
('Pérdiddpesinexplicable'),
('Sueñfragmentado'),
('Npueddormir'),
('Insomnio')

INSERT INTO Answers(Aswer) VALUES
('Si'), ('No'), ('No Aplica')